### ISSUE TITLE
Write an "introduction email"

### ISSUE THREAD

**Issue by mithro** [mithro/duck2-gsoc#10]
As part of getting involved in the SymbiFlow community as a GSoC student, you should write and send an introductory email to the the mailing list to introduce your project to the wider community. This email should be proofread by your mentor and only sent out **after their approval**.

The email subject should be something like "GSoC Project 2019: <project name>, <student name>" and should be sent to the main list, https://lists.librecores.org/listinfo/symbiflow

This email should include;
 * A short paragraph explaining your project.
 * A URL to a Google Doc containing your project proposal.
 * A URL for your "GSoC Progress Blog", see below (plus link to the RSS feed).
 * A link with your github username.
 * A little bit about yourself (include a couple of fun facts!)

**Comment by duck2** [comment]
I'm thinking about something like this:

> Hello!
>
> I'm duck2\[0\], this year's Google Summer of Code student for SymbiFlow.
>
> In this summer, I'm going to work on the VPR file formats. The project proposal\[1\]
> includes a schema-generated reader for the arch.xml file and a binary format
> for the rr_graph.xml file(and other intermediate files). I'll also try to generate the rr_graph
> from more succinct formats like tileconn.json instead of dumping the whole graph into the file.
> I'll record my progress on all this at https://gsoc.duck2.lt.
>
> About me: I'm an 4th year EEE student from METU\[2\], Turkey. Programming computers
> is my longest lasting hobby so far, after chemistry, orienteering and macroeconomics.
> I'm interested in SymbiFlow because current FPGA CAD software is ...not good.
>
> \[0\]: https://github.com/duck2
> \[1\]: https://docs.google.com/document/d/1bxVSlnD2vfiWvrIwesxh0HMK4LLZORN8s4ZDm8yQ5WY
> \[2\]: https://en.wikipedia.org/wiki/Middle_East_Technical_University

<blockquote><div><strong><a href="https://gsoc.duck2.lt/">duck2-gsoc</a></strong></div></blockquote>
<blockquote><img src="https://avatars0.githubusercontent.com/u/12058255?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/duck2">duck2 - Overview</a></strong></div><div>sometimes green, sometimes white
. duck2 has 19 repositories available. Follow their code on GitHub.</div></blockquote>
<blockquote><img src="https://lh3.googleusercontent.com/0ahGvkEHrwgITDXVWfg9DWxz1qgnTJyThSDyPl7YPPw9FWELjFb5FWYcJ0qCiyoR-StRsw=w1200-h630-p" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://docs.google.com/document/d/1bxVSlnD2vfiWvrIwesxh0HMK4LLZORN8s4ZDm8yQ5WY/edit?usp=embed_facebook">GSoC Proposal: Optimization of VPR File Formats</a></strong></div><div>GSoC Proposal: Optimization of VPR File Formats  Fahrican Koşar(@duck2 at IRC, duck2@protonmail.com) Synopsis  I propose replacing VPR’s XML reader for the architecture file with a schema-generated one. Furthermore, I propose replacing current rr_graph, top.net, route and place formats with more ...</div></blockquote>
<blockquote><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Logo_of_METU.svg/1200px-Logo_of_METU.svg.png" width="48" align="right"><div><strong><a href="https://en.wikipedia.org/wiki/Middle_East_Technical_University">Middle East Technical University - Wikipedia</a></strong></div></blockquote>

**Comment by mithro** [comment]
Can you dump this into a Google Doc so I can add some comments?

**Comment by duck2** [comment]
here it is: https://docs.google.com/document/d/1FyoyJ4Yw0vLctYfRamz00LQsN51VQbuge-fhC6Krvtc/

**Comment by mithro** [comment]
@duck2 - Added a bunch of comments to your doc. Do you want to look over it and we can try and send it out in the next day or two?

**Comment by duck2** [comment]
I did some minor changes. I can send it tomorrow if it is OK.

**Comment by mithro** [comment]
I added a couple of small changes.

Please send it to https://lists.librecores.org/listinfo/symbiflow and https://groups.google.com/forum/#!members/vtr-devel

<blockquote><div><strong><a href="https://lists.librecores.org/listinfo/symbiflow">SymbiFlow Info Page</a></strong></div></blockquote>
<blockquote><img src="favicon.ico" width="48" align="right"><div><strong><a href="https://groups.google.com/forum/#!members/vtr-devel">Google Groups</a></strong></div><div>Google Groups allows you to create and participate in online forums and email-based groups with a rich experience for community conversations.</div></blockquote>
