### ISSUE TITLE
Create a Google Calendar

### ISSUE THREAD

**Issue by mithro** [mithro/duck2-gsoc#11]
To help keep track of your planning, please create a Google Calendar. This calendar should include commitments you have (such as conferences, holidays, exams, etc) and timeline for ordering parts, your weekly video conference, etc. An example of such a calendar for a past student can be found at;

https://www.google.com/calendar/embed?src=pgmrl9mp6d880m4bejqghdirm8@group.calendar.google.com see April 2014

**Comment by duck2** [comment]
oops, i cannot see the events there

**Comment by mithro** [comment]
Looks like I don't either! Guess the calendar was probably deleted or something.

Basically just want a calendar with periods marked when you have other commitments like exams and such.

**Comment by duck2** [comment]
I created one [here](https://calendar.google.com/calendar/b/1/embed?src=duck2@protonmail.com&ctz=Europe/Istanbul).

**Comment by mithro** [comment]
Great! I seem to be able to access it. Looks like you have midterms until end of April and will be mostly free from the start of May?
