### ISSUE TITLE
Create a "GSoC Progress Blog"

### ISSUE THREAD

**Issue by mithro** [mithro/duck2-gsoc#9]
During GSoC we required you to have a "blog" to post progress of your project on. You can use any hosting platform you like (Blogger, Wordpress, GitHub Pages etc) or even host your own. If you already have a blog, you could also use a special category for GSoC if you want. The two requirements for the software are;

 * Provide a dedicated RSS or Atom feed of the GSoC posts.
 * Provide an ability for people to comment on your GSoC posts.
 * Provide an ability for people to be notified about a response to their comments.

During the GSoC period, you will be expected to;
 * Daily, create "snippets" and post them to your blog.
 * Weekly, "progress reports" and post them to your blog.

Until GSoC coding period officially starts, you are not required to do the daily snippets but if you do any work a short version of the progress reports would be good. We also need to decide on which day of the week you will post your progress reports.

You are encourage to read other students blogs!

**Comment by duck2** [comment]
I created a Blogger at [gsoc.duck2.lt](https://gsoc.duck2.lt).

The RSS feed is [here](https://gsoc.duck2.lt/feeds/posts/default?alt=rss).

**Comment by mithro** [comment]
@duck2 - I was able to see the blog, comment on it and subscribe to the RSS feed.
